#!/usr/bin/env ruby

require 'optparse'
require 'oneenvHelper'

options = {}

optparse = OptionParser.new do|opt|
  opt.banner = "Usage: oneenv COMMAND [OPTIONS]"
  opt.separator  ""
  opt.separator  "Commands"
  opt.separator  "     create: Creates a new Enviroment."#create NAME ID_TEMPLATE NODE_PATH [-p DATABAG_PATH]
  opt.separator  "     list: Lists all Enviroments." # list
  opt.separator  "     clone: Clones an existing Enviroment" #clone ID_Env
  opt.separator  "     show: Prints the information of an existing Enviroment" #show ID_Env
  opt.separator  "     delete : Deletes an existing Enviroment" #delete ID_Env
  opt.separator  "     update-node : Changes the path of the Enviroment's node" #update-node ID_ENV [NODE_PATH]
  opt.separator  "     set-databags: Sets a Databag path to an existing Enviroment" #set-databags ID_ENV [DB_PATH]
  opt.separator  "     up: " #up ID_entorno [CHEF_PATH]
  opt.separator  "     add-role-dir: Adds a Role path" #add-role-dir PATH
  opt.separator  "     update-role: Updates the given Role" #update-role NAME
  opt.separator  "     list-roles: Lists the Roles" #list-roles
  opt.separator  "     delete-role: Deletes a given Role" #delete-role NAME
  opt.separator  ""
  opt.separator  "Options"

   options[:aux_path] = nil
   opt.on( '-p', '--path PATH', 'This is the databag,chef or node path' ) do |path|
     options[:aux_path] = path
   end

  opt.on("-h","--help","help") do
    puts opt_parser
  end


end


begin 
optparse.parse!

PATH_AUX=options[:aux_path]		

case ARGV[0]

	when 'create'
		raise ArgumentError if ARGV.length !=4 
		NAME=ARGV[1]
		ID=ARGV[2]
		N_PATH=ARGV[3]
		OneEnvHelper.create(NAME,ID,N_PATH,PATH_AUX)		

	when "list"
		raise ArgumentError if ARGV.length != 1
		OneEnvHelper.list()
	
	when "clone"
		raise ArgumentError if ARGV.length != 2
		ID=ARGV[1]
		OneEnvHelper.clone(ID)

	when "show"
		raise ArgumentError if ARGV.length != 2
		ID=ARGV[1]
		OneEnvHelper.show(ID)

	when "delete"
		raise ArgumentError if ARGV.length != 2
		ID=ARGV[1]
		OneEnvHelper.delete(ID)

	when "update-node"
		raise ArgumentError if ARGV.length != 2
		ID=ARGV[1]
		OneEnvHelper.updateNode(ID,PATH_AUX)

	when "set-databags"
		#DB_PATH creo que es un argumento obligatorio
		raise ArgumentError if ARGV.length != 3  		
		ID=ARGV[1]
		DB_PATH=ARGV[2]
		OneEnvHelper.setDatabag(ID,DB_PATH)

	when "up"
		raise ArgumentError if ARGV.length != 2
		ID=ARGV[1]
		OneEnvHelper.up(ID, PATH_AUX)

	when "add-role-dir"
		raise ArgumentError if ARGV.length != 2 
		PATH=ARGV[1]
		OneEnvHelper.addRoleDir(PATH)

	when "update-role"
		raise ArgumentError if ARGV.length != 2 
		NAME=ARGV[1]
		OneEnvHelper.updateRole(NAME)

	when "list-roles"
		raise ArgumentError if ARGV.length != 1 
		OneEnvHelper.listRoles()

	when "delete-role"
		raise ArgumentError if ARGV.length != 2 
		NAME=ARGV[1]
		OneEnvHelper.deleteRole(NAME)

	else
	  puts optparse
	end

rescue OptionParser::InvalidOption, OptionParser::MissingArgument,ArgumentError
		puts optparse
		exit

end

